services:
  frontend:
    container_name: frontend
    build:
      context: ./IH-webapp
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=web-db
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: mysql:8.0.37
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: web-db
    volumes:
      - mysql_data:/var/lib/mysql             
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
