services:
  frontend:
    container_name: frontend
    build:
      context: ./IH-webapp
      dockerfile: Dockerfile
    image: phantasm1/insight-harbor-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: phantasm1/insight-harbor-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Ph05221838.
      DB_NAME: web-db
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: mysql:8.0.37
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Ph05221838.
      MYSQL_DATABASE: web-db
    volumes:
      - mysql_data:/var/lib/mysql             
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
